title: Matt Glen
email: mwglen@ncsu.edu
baseurl: ""
url: "https://mattglen.dev"
github_username: mwglen

# Build settings
remote_theme: jekyll/minima
minima:
    skin: dark
    social_links:
        github: mwglen
        linkedin: matthew-w-glen
header_pages:
    - projects.md
    - education.md
    - experience.md
    - skills.md

plugins:
    - jekyll-feed

exclude:
   - Gemfile
   - Gemfile.lock
   - flake.nix
   - flake.lock

