title: Matt Glen
email: mwglen@ncsu.edu
description: >-
    Matthew Glen is ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattglen.dev"
github_username:  mwglen

# Build settings
remote_theme: jekyll/minima
minima:
    skin: dark
    social_links:
        github: mwglen
header_pages:
    - projects.md
    - about.md

plugins:
    - jekyll-feed

exclude:
   - Gemfile
   - Gemfile.lock
   - flake.nix
   - flake.lock

